# Generated by Django 4.2.1 on 2023-05-14 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='anyThing', null=True)),
                ('instructor_name', models.CharField(max_length=255)),
                ('numbers_of_students', models.IntegerField(max_length=1000)),
            ],
        ),
    ]
